# Generated by Django 5.2.3 on 2025-07-07 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueauthentification',
            name='role_autorise',
            field=models.CharField(blank=True, help_text='Rôle autorisé pour cet utilisateur', max_length=20),
        ),
        migrations.AddField(
            model_name='historiqueauthentification',
            name='role_tente',
            field=models.CharField(blank=True, help_text='Rôle tenté lors de la connexion', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='bloque_par_admin',
            field=models.ForeignKey(blank=True, help_text='Admin qui a bloqué cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_bloques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_blocage',
            field=models.DateTimeField(blank=True, help_text='Date de blocage', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_tentative_incorrecte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_bloque',
            field=models.BooleanField(default=False, help_text='Utilisateur bloqué pour violation de sécurité'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='raison_blocage',
            field=models.TextField(blank=True, help_text='Raison du blocage'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_autorise',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('patient', 'Patient')], help_text='Rôle autorisé pour cet utilisateur', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tentatives_connexion_incorrectes',
            field=models.IntegerField(default=0, help_text='Nombre de tentatives de connexion incorrectes'),
        ),
        migrations.AlterField(
            model_name='historiqueauthentification',
            name='type_auth',
            field=models.CharField(choices=[('NFC_CARTE', 'Authentification par carte NFC'), ('EMPREINTE_NFC', 'Authentification par empreinte NFC'), ('TENTATIVE_ROLE_INCORRECT', 'Tentative de connexion avec rôle incorrect'), ('AUTRE', 'Autre méthode')], max_length=30),
        ),
        migrations.CreateModel(
            name='AlerteSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('TENTATIVE_ROLE_INCORRECT', 'Tentative de connexion avec un rôle incorrect'), ('BLOQUAGE_UTILISATEUR', 'Utilisateur bloqué'), ('DEBLOQUAGE_UTILISATEUR', 'Utilisateur débloqué'), ('TENTATIVE_ACCES_NON_AUTORISE', "Tentative d'accès non autorisé"), ('VIOLATION_SECURITE', 'Violation de sécurité')], max_length=50)),
                ('details', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('niveau_urgence', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('adresse_ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('admin_qui_a_bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_crees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de sécurité',
                'verbose_name_plural': 'Alertes de sécurité',
                'ordering': ['-date_creation'],
            },
        ),
    ]
