# Generated by Django 5.2.3 on 2025-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_historiqueauthentification_role_autorise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role_demande',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('patient', 'Patient')], help_text="Rôle souhaité par l'utilisateur à l'inscription", max_length=20, null=True),
        ),
    ]
