# Generated by Django 5.2.3 on 2025-07-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_utilisateur_role_demande'),
    ]

    operations = [
    ]
