# Generated by Django 5.2.3 on 2025-07-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_auto_20250707_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceAcceptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_licence', models.CharField(choices=[('POLITIQUE_CONFIDENTIALITE', 'Politique de confidentialité'), ('CONDITIONS_UTILISATION', "Conditions d'utilisation"), ('LICENCE_MEDICALE', 'Licence médicale')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('date_acceptation', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences_acceptees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceptation de licence',
                'verbose_name_plural': 'Acceptations de licences',
                'ordering': ['-date_acceptation'],
                'unique_together': {('utilisateur', 'type_licence', 'version')},
            },
        ),
    ]
