# Generated by Django 5.2.3 on 2025-07-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_auto_20250707_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertesecurite',
            name='type_alerte',
            field=models.CharField(choices=[('TENTATIVE_ROLE_INCORRECT', 'Tentative de connexion avec un rôle incorrect'), ('BLOQUAGE_UTILISATEUR', 'Utilisateur bloqué'), ('DEBLOQUAGE_UTILISATEUR', 'Utilisateur débloqué'), ('CREATION_UTILISATEUR', "Création d'utilisateur par l'administrateur"), ('TENTATIVE_ACCES_NON_AUTORISE', "Tentative d'accès non autorisé"), ('VIOLATION_SECURITE', 'Violation de sécurité')], max_length=50),
        ),
    ]
