# Generated by Django 5.2.3 on 2025-07-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_licenceacceptation'),
    ]

    operations = [
    ]
