# Generated by Django 5.2.3 on 2025-07-12 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_add_licence_acceptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('LECTURE_DONNEES', 'Lecture de données'), ('MODIFICATION_DONNEES', 'Modification de données'), ('SUPPRESSION_DONNEES', 'Suppression de données'), ('ACCES_MEDICAL', 'Accès aux données médicales'), ('ACCES_PATIENT', 'Accès aux données patient'), ('BLOQUAGE_UTILISATEUR', "Blocage d'utilisateur"), ('DEBLOQUAGE_UTILISATEUR', "Déblocage d'utilisateur"), ('VIOLATION_SECURITE', 'Violation de sécurité')], max_length=50)),
                ('description', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('url_accedee', models.CharField(blank=True, max_length=500)),
                ('donnees_consultees', models.TextField(blank=True, help_text='Données consultées (chiffrées)')),
                ('niveau_risque', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('est_suspect', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['utilisateur', 'date_heure'], name='comptes_aud_utilisa_883f1e_idx'), models.Index(fields=['type_action', 'date_heure'], name='comptes_aud_type_ac_e3a5ad_idx'), models.Index(fields=['niveau_risque', 'date_heure'], name='comptes_aud_niveau__58a6e8_idx')],
            },
        ),
    ]
