# Generated by Django 5.2.3 on 2025-07-16 06:21

import comptes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_alertesecurite_type_alerte_rfidcard_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='badge_bleu_uid',
            field=comptes.models.EncryptedTextField(blank=True, help_text='UID badge bleu (visible admin uniquement)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='rfid_uid',
            field=comptes.models.EncryptedTextField(blank=True, help_text='UID carte RFID (visible admin uniquement)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='badge_bleu_uid',
            field=comptes.models.EncryptedTextField(blank=True, help_text='UID badge bleu (visible admin uniquement)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rfid_uid',
            field=comptes.models.EncryptedTextField(blank=True, help_text='UID carte RFID (visible admin uniquement)', null=True, unique=True),
        ),
    ]
