# Generated by Django 5.2.3 on 2025-07-23 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_medecin_badge_bleu_uid_medecin_rfid_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('motif_consultation', models.TextField()),
                ('symptomes', models.TextField(blank=True)),
                ('examen_clinique', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('traitement_prescrit', models.TextField(blank=True)),
                ('examens_complements', models.TextField(blank=True, help_text='Examens complémentaires prescrits')),
                ('observations', models.TextField(blank=True)),
                ('prochaine_visite', models.DateField(blank=True, null=True)),
                ('confidentialite', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('resultat_examen', "Résultat d'examen"), ('courrier_medical', 'Courrier médical'), ('imagerie', 'Imagerie médicale'), ('autres', 'Autres')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, upload_to='documents_medicaux/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MedecinNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(default='NON_RENSEIGNE', help_text="Numéro d'ordre du conseil médical", max_length=20, unique=True)),
                ('telephone_cabinet', models.CharField(blank=True, max_length=20)),
                ('adresse_cabinet', models.TextField(blank=True)),
                ('horaires_consultation', models.TextField(blank=True, help_text='Horaires de consultation')),
                ('tarif_consultation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepte_nouveaux_patients', models.BooleanField(default=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'db_table': 'comptes_medecin_new',
            },
        ),
        migrations.CreateModel(
            name='PatientNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, unique=True)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('allergies_connues', models.TextField(blank=True)),
                ('antecedents_medicaux', models.TextField(blank=True)),
                ('personne_a_contacter_nom', models.CharField(blank=True, max_length=100)),
                ('personne_a_contacter_telephone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'comptes_patient_new',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.TextField()),
                ('duree_traitement', models.CharField(max_length=100)),
                ('instructions_particulieres', models.TextField(blank=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='SpecialiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Spécialité médicale',
                'verbose_name_plural': 'Spécialités médicales',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='medecin_referent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='utilisateur',
        ),
        migrations.AlterModelOptions(
            name='dossiermedical',
            options={'verbose_name': 'Dossier médical', 'verbose_name_plural': 'Dossiers médicaux'},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['date_rdv'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.RemoveConstraint(
            model_name='rendezvous',
            name='unique_medecin_time',
        ),
        migrations.RemoveConstraint(
            model_name='rendezvous',
            name='unique_patient_time',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='date_heure',
            new_name='date_rdv',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='path_fichier',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='resume',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='notes_importantes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('transfere', 'Transféré')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='duree_prevue',
            field=models.IntegerField(default=30, help_text='Durée en minutes'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='notes_secretariat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='type_rdv',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('visite_controle', 'Visite de contrôle'), ('urgence', 'Urgence'), ('teleconsultation', 'Téléconsultation')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Patient absent')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptes.rendezvous'),
        ),
        migrations.AddField(
            model_name='documentmedical',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmedical',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='comptes.dossiermedical'),
        ),
        migrations.AddField(
            model_name='medecinnew',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medecin_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='comptes.medecinnew'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='comptes.medecinnew'),
        ),
        migrations.AddField(
            model_name='patientnew',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='comptes.medecinnew'),
        ),
        migrations.AddField(
            model_name='patientnew',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_patient_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='comptes.patientnew'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='comptes.patientnew'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='comptes.patientnew'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='comptes.consultation'),
        ),
        migrations.AddField(
            model_name='medecinnew',
            name='specialites',
            field=models.ManyToManyField(blank=True, to='comptes.specialitemedicale'),
        ),
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
